import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script defer src="https://sdk.zebline.io/js/v1/sgm-sdk.js"></script>
      </head>
      <body className={inter.className}>
        <div>{children}</div>

        <Script
          id="show-banner"
          dangerouslySetInnerHTML={{
            __html: ` window.zebline.init({
            token: "bearer 4$U2VnbWVudCFuMA$TyBLdeYwC71684835503713",
            licence_code: "4$U2VnbWVudCFuMA$SCA9IOb4gf1684835503794",
            notificationRequest: true,
          }); `
          }}
        />
      </body>
    </html>
  )
}
